- name: creation of ec2 and r53
  hosts: localhost
  connection: local
  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-08570272f74f280e0
    zone_id: "Z0703152351ZHIBULK5Q0"
    domain_name: "thiscomeback.fun"
    # we can pass instance thorugh command line
    # instance:
    #   - mongodb
    #   - redis
    #   - mysql
    #   - rabbitmq

  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output

    # - name: print ec2 output
    #   ansible.builtin.debug:
    #     msg: "{{ ec2_output }}"

    - name: create route53 recordd
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}.{{ domain_name }}" # mongodb.daws86s.fun
        type: A
        ttl: 2
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"
    
    #creating record for public ip only for front end

    - name: create route53 record for front
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ domain_name }}" # mongodb.daws86s.fun
        type: A
        ttl: 2
        value: "{{ item.instances[0].public_ip_address }}"
        overwrite: true
      when: item.item == "frontend"
      loop: "{{ ec2_output.results }}"



    # - name: print the public ip of the instance
    #   ansible.builtin.debug:
    #     msg: "{{ item.instances[0].public_ip_address }}"
    #   loop: "{{ ec2_output.results }}"

    # - name: print the private ip of the instance
    #   ansible.builtin.debug:
    #     msg: "{{ item.instances[0].private_ip_address }}"
    #   loop: "{{ ec2_output.results }}"

