[mongodb]
mongodb.thiscomeback.fun

[redis]
redis.thiscomeback.fun

[mysql]
mysql.thiscomeback.fun

[rabbitmq]
rabbitmq.thiscomeback.fun

[catalogue]
catalogue.thiscomeback.fun

[cart]
cart.thiscomeback.fun

[user]
user.thiscomeback.fun

[shipping]
shipping.thiscomeback.fun

[payment]
payment.thiscomeback.fun

[frontend]
frontend.thiscomeback.fun


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local]
localhost



